#--------------------------通用配置-------------------------
spring:
  application:
    # 应用名
    name: vediosharing
  jackson:
    generator:
      # JSON 序列化时，将所有 Number 类型的属性都转为 String 类型返回，避免前端数据精度丢失的问题。
      # 由于 Javascript 标准规定所有数字处理都应使用 64 位 IEEE 754 浮点值完成，
      # 结果是某些 64 位整数值无法准确表示（尾数只有 51 位宽）
      write-numbers-as-strings: true
  servlet:
    multipart:
      # 上传文件最大大小
      max-file-size: 5MB
server:
  # 端口号
  port: 3003

--- #---------------------数据库配置---------------------------
spring:
  datasource:
    url: url
    username: name
    password: psw
    driver-class-name: com.mysql.cj.jdbc.Driver
  # ShardingSphere-JDBC 配置
  # 配置是 ShardingSphere-JDBC 中唯一与应用开发者交互的模块，
  # 通过它可以快速清晰的理解 ShardingSphere-JDBC 所提供的功能。v

--- #---------------------中间件配置---------------------------
spring:
  data:
    # Redis 配置
    redis:
      host: url
      port: port
      password: psw